name: Build and Mirror Docker Images with Bashbrew

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  packages: write # Allows pushing to GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install Bashbrew
      uses: docker-library/bashbrew@d23b94357ef16d21a8d14578d5338152e4460c91 # v0.1.12

    - name: Set up Docker Buildx
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Clone Official Images Repo
      run: git clone https://github.com/docker-library/official-images.git /home/runner/docker/official-images

    - name: Build and Push Docker Images with Bashbrew
      env:
        BASHBREW_BUILDKIT_SYNTAX: "docker/dockerfile:1@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28"
        BASHBREW_ARCHITECTURES: "amd64 arm64v8 ppc64le s390x"
      run: |
        cd /home/runner/docker/official-image

        # Process only the eclipse-temurin repo
        bashbrew list eclipse-temurin | while read -r entry; do
          echo "Processing entry: $entry"

          # Build and push the image for all architectures defined in the manifest
          bashbrew build "$entry"
          bashbrew push "$entry"
        done
